name: 'Infraestrutura: EKS Dev'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Ação a executar (apply ou destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
# Variáveis globais para o Runner
env:
  TF_VERSION: "1.10.5" # Versão segura do Terraform (OpenTofu compatible se precisar)
  TG_VERSION: "0.55.0" # Versão recente do Terragrunt
  WORKING_DIR_VPC: "live/dev/vpc/" # Apontando para a pasta "pai" do ambiente de desenvolvimento
  WORKING_DIR_EKS: "live/dev/eks/" # Apontando para a pasta "pai" do ambiente de desenvolvimento  
jobs:
  terragrunt-vpc:
    name: 'Create VPC Dev'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout do Repositório'
        uses: actions/checkout@v4

      - name: 'Instalar Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: 'Instalar Terragrunt'
        run: |
          wget -q -O terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TG_VERSION }}/terragrunt_linux_amd64"
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt
          terragrunt --version

      - name: 'Configurar Credenciais da AWS'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 'Terragrunt Init'
        working-directory: ${{ env.WORKING_DIR_VPC }}
        run: terragrunt init --terragrunt-non-interactive

      - name: 'Terragrunt Plan'
        working-directory: ${{ env.WORKING_DIR_VPC }}
        run: terragrunt plan --terragrunt-non-interactive

      #  O GATILHO MANUAL (Botão de Emergência: Roda Apply ou Destroy)
      - name: 'Terragrunt Action (Manual)'
        if: github.event_name == 'workflow_dispatch'
        working-directory: ${{ env.WORKING_DIR_VPC }}
        run: terragrunt ${{ github.event.inputs.action }} --auto-approve --terragrunt-non-interactive
      # O APPLY SÓ RODA SE FOR UM PUSH NA MAIN (Não roda em PRs)
      - name: 'Terragrunt Apply'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ${{ env.WORKING_DIR_VPC }}
        run: terragrunt apply --auto-approve --terragrunt-non-interactive
  terragrunt-eks:
    needs: terragrunt-vpc
    name: 'Create EKS Cluster'
    runs-on: ubuntu-latest
    

    steps:
      - name: 'Checkout do Repositório'
        uses: actions/checkout@v4

      - name: 'Instalar Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: 'Instalar Terragrunt'
        run: |
          wget -q -O terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TG_VERSION }}/terragrunt_linux_amd64"
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt
          terragrunt --version

      - name: 'Configurar Credenciais da AWS'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 'Terragrunt Init'
        working-directory: ${{ env.WORKING_DIR_EKS }}
        run: terragrunt init --terragrunt-non-interactive

      - name: 'Terragrunt Plan'
        working-directory: ${{ env.WORKING_DIR_EKS }}
        run: terragrunt plan --terragrunt-non-interactive

      #  O GATILHO MANUAL (Botão de Emergência: Roda Apply ou Destroy)
      - name: 'Terragrunt Action (Manual)'
        if: github.event_name == 'workflow_dispatch'
        working-directory: ${{ env.WORKING_DIR_EKS }}
        run: terragrunt ${{ github.event.inputs.action }} --auto-approve --terragrunt-non-interactive
      # O APPLY SÓ RODA SE FOR UM PUSH NA MAIN (Não roda em PRs)
      - name: 'Terragrunt Apply'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ${{ env.WORKING_DIR_EKS }}
        run: terragrunt apply --auto-approve --terragrunt-non-interactive